#!/bin/zsh

#
# INIT
#

# get name of the project to init
project_name=$1
# get the real path of the exec script
exec_dir=$(dirname `perl -e 'use Cwd "abs_path";print abs_path(shift)' $0`)
#
tmp_file="/tmp/42init-$$"

#
# RUN
#

if [[ -d ${project_name} ]]; then
	echo "Directory " ${project_name} " already exists." && exit 1
fi

mkdir ${project_name}

pushd ${project_name}

cp -a ${exec_dir}/skel/* ./

mv gitignore .gitignore

sed s/PROJECT_NAME/"${project_name}"/g Makefile > ${tmp_file} && mv ${tmp_file} Makefile
sed s/PROJECT_NAME/"${project_name}"/g .gitignore > ${tmp_file} && mv ${tmp_file} .gitignore

echo `whoami` > auteur

echo "# "${project_name} > README.md

git init .

git submodule add https://github.com/`whoami`/libft.git

git add -A .

git commit -m "Initial commit"

popd
